[[plugins]]
repo = "Shougo/deoplete.nvim"

[[plugins]]
repo = "dhruvasagar/vim-table-mode"
hook_add = '''source ~/.config/nvim/plugins/vim-table-mode.vim'''

[[plugins]]
repo = "iamcco/markdown-preview.nvim"
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'sh -c "cd app & yarn install & npm install"'
